/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v0.1.56), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

import type {
  JSONValue,
  JSONArray,
  DateString,
  SQLFragment,
  SQL,
  GenericSQLExpression,
  ColumnNames,
  ColumnValues,
  Parameter,
  ParentColumn,
  DefaultType,
} from './src/core';


/* === schema: public === */

/* --- enums --- */


/* --- tables --- */

export declare namespace employee {
  export type Table = 'employee';
  export interface Selectable {
    id: number;
    employee_number: number;
    name: string;
    email_address: string;
    password_hash: string;
    is_admin: boolean;
  }
  export interface Insertable {
    id: number | Parameter<number> | SQLFragment;
    employee_number: number | Parameter<number> | SQLFragment;
    name: string | Parameter<string> | SQLFragment;
    email_address: string | Parameter<string> | SQLFragment;
    password_hash: string | Parameter<string> | SQLFragment;
    is_admin: boolean | Parameter<boolean> | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'employee_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

export declare namespace job {
  export type Table = 'job';
  export interface Selectable {
    id: number;
    name: string;
    description: string;
    hours_std: number;
    hours_short: number;
    hours_long: number;
    hours_std_banked: number;
    hours_short_banked: number;
    hours_long_banked: number;
    pay_period_id: number;
  }
  export interface Insertable {
    id: number | Parameter<number> | SQLFragment;
    name: string | Parameter<string> | SQLFragment;
    description: string | Parameter<string> | SQLFragment;
    hours_std: number | Parameter<number> | SQLFragment;
    hours_short: number | Parameter<number> | SQLFragment;
    hours_long: number | Parameter<number> | SQLFragment;
    hours_std_banked: number | Parameter<number> | SQLFragment;
    hours_short_banked: number | Parameter<number> | SQLFragment;
    hours_long_banked: number | Parameter<number> | SQLFragment;
    pay_period_id: number | Parameter<number> | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'job_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

export declare namespace pay_period {
  export type Table = 'pay_period';
  export interface Selectable {
    id: number;
    date: Date;
    employee_id: number;
  }
  export interface Insertable {
    id: number | Parameter<number> | SQLFragment;
    date: Date | Parameter<Date> | DateString | SQLFragment;
    employee_id: number | Parameter<number> | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'pay_period_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

/* === cross-table types === */

export type Table = employee.Table | job.Table | pay_period.Table;
export type Selectable = employee.Selectable | job.Selectable | pay_period.Selectable;
export type Whereable = employee.Whereable | job.Whereable | pay_period.Whereable;
export type Insertable = employee.Insertable | job.Insertable | pay_period.Insertable;
export type Updatable = employee.Updatable | job.Updatable | pay_period.Updatable;
export type UniqueIndex = employee.UniqueIndex | job.UniqueIndex | pay_period.UniqueIndex;
export type Column = employee.Column | job.Column | pay_period.Column;
export type AllTables = [employee.Table, job.Table, pay_period.Table];


export type SelectableForTable<T extends Table> = {
  employee: employee.Selectable;
  job: job.Selectable;
  pay_period: pay_period.Selectable;
}[T];

export type WhereableForTable<T extends Table> = {
  employee: employee.Whereable;
  job: job.Whereable;
  pay_period: pay_period.Whereable;
}[T];

export type InsertableForTable<T extends Table> = {
  employee: employee.Insertable;
  job: job.Insertable;
  pay_period: pay_period.Insertable;
}[T];

export type UpdatableForTable<T extends Table> = {
  employee: employee.Updatable;
  job: job.Updatable;
  pay_period: pay_period.Updatable;
}[T];

export type UniqueIndexForTable<T extends Table> = {
  employee: employee.UniqueIndex;
  job: job.UniqueIndex;
  pay_period: pay_period.UniqueIndex;
}[T];

export type ColumnForTable<T extends Table> = {
  employee: employee.Column;
  job: job.Column;
  pay_period: pay_period.Column;
}[T];

export type SQLForTable<T extends Table> = {
  employee: employee.SQL;
  job: job.SQL;
  pay_period: pay_period.SQL;
}[T];

